//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contoso.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Contoso.Common.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magnus Hedlund (Developer).
        /// </summary>
        internal static string NewsItem1_Author {
            get {
                return ResourceManager.GetString("NewsItem1_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to encarta@botmetro.net.
        /// </summary>
        internal static string NewsItem1_AuthorPrecenseID {
            get {
                return ResourceManager.GetString("NewsItem1_AuthorPrecenseID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When Blue Yonder Airline抯 customers demanded a smoother ride, Contoso delivered. With the new airline system implemented Blue Yonder customers now wait 16 hours less in airports each day and stockholders are seeing greater returns..
        /// </summary>
        internal static string NewsItem1_Description {
            get {
                return ResourceManager.GetString("NewsItem1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css/news_thumb_001.png.
        /// </summary>
        internal static string NewsItem1_Image {
            get {
                return ResourceManager.GetString("NewsItem1_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contoso builds new airline system for Blue Yonder Airlines.
        /// </summary>
        internal static string NewsItem1_Title {
            get {
                return ResourceManager.GetString("NewsItem1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ray Mike (Developer).
        /// </summary>
        internal static string NewsItem2_Author {
            get {
                return ResourceManager.GetString("NewsItem2_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to encarta@botmetro.net.
        /// </summary>
        internal static string NewsItem2_AuthorPrecenseID {
            get {
                return ResourceManager.GetString("NewsItem2_AuthorPrecenseID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entire corporate presence of Adventure Works has been rebuilt by Contoso. Studies have shown that the new brand for Adventure Works has increased customer acquisition by 25% and customer loyalty by 87%..
        /// </summary>
        internal static string NewsItem2_Description {
            get {
                return ResourceManager.GetString("NewsItem2_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css/new_thumbs_002.png.
        /// </summary>
        internal static string NewsItem2_Image {
            get {
                return ResourceManager.GetString("NewsItem2_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adventure Works reworked by Contoso.
        /// </summary>
        internal static string NewsItem2_Title {
            get {
                return ResourceManager.GetString("NewsItem2_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to David Johnson (Developer).
        /// </summary>
        internal static string NewsItem3_Author {
            get {
                return ResourceManager.GetString("NewsItem3_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to encarta@botmetro.net.
        /// </summary>
        internal static string NewsItem3_AuthorPrecenseID {
            get {
                return ResourceManager.GetString("NewsItem3_AuthorPrecenseID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At 1c per share this was a dream for the Contoso team to buy all 37 shares. The acquisition of Northwind will allow Contoso to expand into new markets and the high performance team will be integrated quickly into Contoso..
        /// </summary>
        internal static string NewsItem3_Description {
            get {
                return ResourceManager.GetString("NewsItem3_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to css/news_thumb_003.png.
        /// </summary>
        internal static string NewsItem3_Image {
            get {
                return ResourceManager.GetString("NewsItem3_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contoso acquires Northwind for $0.37.
        /// </summary>
        internal static string NewsItem3_Title {
            get {
                return ResourceManager.GetString("NewsItem3_Title", resourceCulture);
            }
        }
    }
}
