//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ContosoBicycleClubWeb {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContosoBicycleClubWeb() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ContosoBicycleClubWeb", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Organize a &lt;a href=&quot;Rides/default.aspx&quot;&gt;bike ride&lt;/a&gt; or &lt;a href=&quot;Events/default.aspx&quot;&gt;special event&lt;/a&gt; in the Lower Mainland or beyond.&lt;/p&gt;
        ///&lt;p&gt;Share your photos, add an interactive map and upload your ride videos. Check out who&apos;s online and chat about your next ride.&lt;/p&gt;.
        /// </summary>
        internal static string AboutContosoLabel {
            get {
                return ResourceManager.GetString("AboutContosoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelLabel {
            get {
                return ResourceManager.GetString("CancelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to chat with other online Contoso riders via Windows Live Messenger..
        /// </summary>
        internal static string ChatNeedLoginLabel {
            get {
                return ResourceManager.GetString("ChatNeedLoginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no Contoso riders available for chat..
        /// </summary>
        internal static string ChatNoUsersLabel {
            get {
                return ResourceManager.GetString("ChatNoUsersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat with Riders Online.
        /// </summary>
        internal static string ChatUsersListHeadingLabel {
            get {
                return ResourceManager.GetString("ChatUsersListHeadingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contoso Username.
        /// </summary>
        internal static string ContosoUsernameLabel {
            get {
                return ResourceManager.GetString("ContosoUsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;#169; 2008 Microsoft.
        /// </summary>
        internal static string CopyrightLabel {
            get {
                return ResourceManager.GetString("CopyrightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string DateLabel {
            get {
                return ResourceManager.GetString("DateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date is required.
        /// </summary>
        internal static string DateRequiredLabel {
            get {
                return ResourceManager.GetString("DateRequiredLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string DescriptionLabel {
            get {
                return ResourceManager.GetString("DescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        internal static string EventCapitalizedLabel {
            get {
                return ResourceManager.GetString("EventCapitalizedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Description.
        /// </summary>
        internal static string EventDescriptionLabel {
            get {
                return ResourceManager.GetString("EventDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Info.
        /// </summary>
        internal static string EventInfoLabel {
            get {
                return ResourceManager.GetString("EventInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to event.
        /// </summary>
        internal static string EventLabel {
            get {
                return ResourceManager.GetString("EventLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        internal static string EventsLabel {
            get {
                return ResourceManager.GetString("EventsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events RSS.
        /// </summary>
        internal static string EventsRSSLabel {
            get {
                return ResourceManager.GetString("EventsRSSLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe to the events RSS feed.
        /// </summary>
        internal static string EventsRSSTooltip {
            get {
                return ResourceManager.GetString("EventsRSSTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event has been updated!.
        /// </summary>
        internal static string EventUpdateSuccessLabel {
            get {
                return ResourceManager.GetString("EventUpdateSuccessLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string HomeLabel {
            get {
                return ResourceManager.GetString("HomeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Events.
        /// </summary>
        internal static string LatestEventsLabel {
            get {
                return ResourceManager.GetString("LatestEventsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Rides.
        /// </summary>
        internal static string LatestRidesLabel {
            get {
                return ResourceManager.GetString("LatestRidesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Messenger Token.
        /// </summary>
        internal static string LiveMessengerTokenLabel {
            get {
                return ResourceManager.GetString("LiveMessengerTokenLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Live Messenger Consent.
        /// </summary>
        internal static string MessengerConsentLabel {
            get {
                return ResourceManager.GetString("MessengerConsentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span&gt;&amp;#187;&lt;/span&gt; More events&amp;#133;.
        /// </summary>
        internal static string MoreEventsLabel {
            get {
                return ResourceManager.GetString("MoreEventsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span&gt;&amp;#187;&lt;/span&gt; More rides&amp;#133;.
        /// </summary>
        internal static string MoreRidesLabel {
            get {
                return ResourceManager.GetString("MoreRidesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organized by:&amp;#160;&amp;#160;.
        /// </summary>
        internal static string OrganizedByLabel {
            get {
                return ResourceManager.GetString("OrganizedByLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organize Your Event.
        /// </summary>
        internal static string OrganizeEventLabel {
            get {
                return ResourceManager.GetString("OrganizeEventLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organize a.
        /// </summary>
        internal static string OrganizeLabel {
            get {
                return ResourceManager.GetString("OrganizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organize Your Ride.
        /// </summary>
        internal static string OrganizeRideLabel {
            get {
                return ResourceManager.GetString("OrganizeRideLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organize your .
        /// </summary>
        internal static string OrganizeYourLabel {
            get {
                return ResourceManager.GetString("OrganizeYourLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        internal static string OrLabel {
            get {
                return ResourceManager.GetString("OrLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Spaces Photo Album RSS URL.
        /// </summary>
        internal static string PhotoAlbumUrlLabel {
            get {
                return ResourceManager.GetString("PhotoAlbumUrlLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos.
        /// </summary>
        internal static string PhotosLabel {
            get {
                return ResourceManager.GetString("PhotosLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        internal static string PrivacyPolicyLabel {
            get {
                return ResourceManager.GetString("PrivacyPolicyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to Events.
        /// </summary>
        internal static string ReturnToEventsLabel {
            get {
                return ResourceManager.GetString("ReturnToEventsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to Rides.
        /// </summary>
        internal static string ReturnToRidesLabel {
            get {
                return ResourceManager.GetString("ReturnToRidesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ride.
        /// </summary>
        internal static string RideCapitalizedLabel {
            get {
                return ResourceManager.GetString("RideCapitalizedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ride Description.
        /// </summary>
        internal static string RideDescriptionLabel {
            get {
                return ResourceManager.GetString("RideDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ride Info.
        /// </summary>
        internal static string RideInfoLabel {
            get {
                return ResourceManager.GetString("RideInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ride.
        /// </summary>
        internal static string RideLabel {
            get {
                return ResourceManager.GetString("RideLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rides.
        /// </summary>
        internal static string RidesLabel {
            get {
                return ResourceManager.GetString("RidesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rides RSS.
        /// </summary>
        internal static string RidesRSSLabel {
            get {
                return ResourceManager.GetString("RidesRSSLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe to the rides RSS feed.
        /// </summary>
        internal static string RidesRSSTooltip {
            get {
                return ResourceManager.GetString("RidesRSSTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ride has been updated!.
        /// </summary>
        internal static string RideUpdateSuccessLabel {
            get {
                return ResourceManager.GetString("RideUpdateSuccessLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route Info.
        /// </summary>
        internal static string RouteInfoLabel {
            get {
                return ResourceManager.GetString("RouteInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveLabel {
            get {
                return ResourceManager.GetString("SaveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your .
        /// </summary>
        internal static string SelectYourLabel {
            get {
                return ResourceManager.GetString("SelectYourLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Contoso riders to chat with you through our website!.
        /// </summary>
        internal static string SharePresenceLabel {
            get {
                return ResourceManager.GetString("SharePresenceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        internal static string SignInLabel {
            get {
                return ResourceManager.GetString("SignInLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        internal static string SignOutLabel {
            get {
                return ResourceManager.GetString("SignOutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silverlight Streaming Video Reference.
        /// </summary>
        internal static string SilverlightStreamingVideoLabel {
            get {
                return ResourceManager.GetString("SilverlightStreamingVideoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail URL.
        /// </summary>
        internal static string ThumbnailUrlLabel {
            get {
                return ResourceManager.GetString("ThumbnailUrlLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string TitleLabel {
            get {
                return ResourceManager.GetString("TitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is required.
        /// </summary>
        internal static string TitleRequiredLabel {
            get {
                return ResourceManager.GetString("TitleRequiredLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming Events.
        /// </summary>
        internal static string UpcomingEventsLabel {
            get {
                return ResourceManager.GetString("UpcomingEventsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming Rides.
        /// </summary>
        internal static string UpcomingRidesLabel {
            get {
                return ResourceManager.GetString("UpcomingRidesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update profile.
        /// </summary>
        internal static string UpdateProfileLabel {
            get {
                return ResourceManager.GetString("UpdateProfileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving. Please wait....
        /// </summary>
        internal static string UploadingLabel {
            get {
                return ResourceManager.GetString("UploadingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Earth Collection ID.
        /// </summary>
        internal static string VECollectionIDLabel {
            get {
                return ResourceManager.GetString("VECollectionIDLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        internal static string VideoLabel {
            get {
                return ResourceManager.GetString("VideoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contoso Riders.
        /// </summary>
        internal static string WebsiteLabel {
            get {
                return ResourceManager.GetString("WebsiteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - .
        /// </summary>
        internal static string WebsiteLabelSeparator {
            get {
                return ResourceManager.GetString("WebsiteLabelSeparator", resourceCulture);
            }
        }
    }
}
